Repository caravan-bitcoin/caravan, pull requests merged in 2025-05, with the labels that each got.

#280 Added contribution templates to streamline PRs and issue reporting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: dx

#142 Caravan UI facelift
  .changeset/many-cooks-move.md
  apps/coordinator/declarations.d.ts
  apps/coordinator/public/images/caravan-logo-transparent.webp
  apps/coordinator/public/images/landing/bitbox.webp
  apps/coordinator/public/images/landing/brave.webp
  apps/coordinator/public/images/landing/caravan-balance.webp
  apps/coordinator/public/images/landing/chrome.webp
  apps/coordinator/public/images/landing/coldcard.webp
  apps/coordinator/public/images/landing/consensus.webp
  apps/coordinator/public/images/landing/firefox.webp
  apps/coordinator/public/images/landing/ledger.webp
  apps/coordinator/public/images/landing/stateless.webp
  apps/coordinator/public/images/landing/trezor.webp
  apps/coordinator/public/images/landing/xpubs.webp
  apps/coordinator/src/components/App.tsx
  apps/coordinator/src/components/Help.tsx
  apps/coordinator/src/components/LandingNav.styles.tsx
  apps/coordinator/src/components/LandingNav.tsx
  apps/coordinator/src/components/LandingPage.styles.tsx
  apps/coordinator/src/components/LandingPage.tsx
  apps/coordinator/src/components/Navbar.jsx
  apps/coordinator/src/components/Setup.tsx
  apps/coordinator/src/components/Wallet/WalletInfoCard.jsx
  apps/coordinator/src/components/Wallet/index.jsx
  apps/coordinator/src/components/styles.css
  apps/coordinator/src/components/theme.js
  apps/coordinator/src/utils/ExternalLink.tsx
Labels: long-lived

#279 migrated `caravan-wallets` to vitest
  apps/coordinator/package.json
  package-lock.json
  packages/caravan-wallets/.eslintrc.json
  packages/caravan-wallets/README.md
  packages/caravan-wallets/jest.config.ts
  packages/caravan-wallets/jest.setup.ts
  packages/caravan-wallets/package.json
  packages/caravan-wallets/src/bcur.test.ts
  packages/caravan-wallets/src/bitbox.ts
  packages/caravan-wallets/src/coldcard.test.ts
  packages/caravan-wallets/src/coldcard.ts
  packages/caravan-wallets/src/constants.ts
  packages/caravan-wallets/src/custom.test.ts
  packages/caravan-wallets/src/custom.ts
  packages/caravan-wallets/src/fixtures.ts
  packages/caravan-wallets/src/fixtures/coldcard.fixtures.ts
  packages/caravan-wallets/src/hermit.test.ts
  packages/caravan-wallets/src/hermit.ts
  packages/caravan-wallets/src/index.ts
  packages/caravan-wallets/src/interaction.test.ts
  packages/caravan-wallets/src/interaction.ts
  packages/caravan-wallets/src/ledger.test.ts
  packages/caravan-wallets/src/ledger.ts
  packages/caravan-wallets/src/policy.test.ts
  packages/caravan-wallets/src/policy.ts
  packages/caravan-wallets/src/trezor.test.ts
  packages/caravan-wallets/src/trezor.ts
  packages/caravan-wallets/tsconfig.json
  packages/caravan-wallets/vitest.config.ts
  packages/caravan-wallets/vitest.setup.ts
Labels: @caravan/wallets, testing
